Feature/map 121/divide components
IT-Academy-Social-Projects-KRV/MapUA pull request #110
Opened 2022-05-31 14:02 UTC by Yojuks

2022-06-01 13:03 UTC, steadyGuy approved these changes

2022-06-01 13:03 UTC, steadyGuy commented on frontend/src/components/Login/Login.tsx
> +/* eslint-disable no-unused-vars */
?

2022-06-01 13:03 UTC, steadyGuy commented on frontend/src/components/Login/Login.tsx
> +// import { useForm, SubmitHandler, useFormState } from 'react-hook-form';
?

2022-06-01 15:21 UTC, mazursasha1990 requested changes

2022-06-01 15:21 UTC, mazursasha1990 commented on frontend/src/components/Login/LoginControllers/LoginControllers.tsx
> +};
Why you didn't remove this file?

2022-06-01 15:21 UTC, mazursasha1990 commented on frontend/src/components/Registration/Controllers/Controllers.tsx
> +};
Why you didn't remove this file?

2022-06-01 15:50 UTC, Yojuks commented on frontend/src/components/Login/Login.tsx
> +// import { useForm, SubmitHandler, useFormState } from 'react-hook-form';
fixed

2022-06-01 15:54 UTC, Yojuks commented on frontend/src/components/Registration/Controllers/Controllers.tsx
> +};
done

2022-06-01 15:54 UTC, Yojuks commented on frontend/src/components/Login/LoginControllers/LoginControllers.tsx
> +};
done

2022-06-01 15:55 UTC, Yojuks commented on frontend/src/components/Login/Login.tsx
> +/* eslint-disable no-unused-vars */
done

2022-06-01 18:18 UTC, naberalgamma approved these changes

2022-06-02 06:41 UTC, Yojuks commented on frontend/src/components/Registration/Controllers/Controllers.tsx
> +};
done

2022-06-02 07:23 UTC, mazursasha1990 requested changes

2022-06-02 07:23 UTC, mazursasha1990 commented on frontend/src/components/Map/ZoomComponent/index.tsx
> +      }
![Screenshot from 2022-06-02 10-14-52](https://user-images.githubusercontent.com/85229023/171574999-7bcec8d6-bfda-4d0f-8586-bcaf3f1a715d.png)

2022-06-02 07:23 UTC, mazursasha1990 commented on frontend/src/components/Profile/EditGroup/EditGroup.tsx
> +import { EditButton, ProfileAvatar, UploadBox } from '../styles';
![Screenshot from 2022-06-02 10-20-13](https://user-images.githubusercontent.com/85229023/171575603-9b1cabb7-3b84-4cb1-bc53-130ab3863489.png)

2022-06-02 07:23 UTC, mazursasha1990 commented on frontend/src/components/Profile/SaveGroup/SaveGroup.tsx
> +import UploadInputProfilePage from 'components/design/UploadInputProfilePage';
![Screenshot from 2022-06-02 10-22-08](https://user-images.githubusercontent.com/85229023/171575939-01829f72-bdc3-4be6-8588-e8a41cb57992.png)

2022-06-02 09:13 UTC, Yojuks commented on frontend/src/components/Profile/EditGroup/EditGroup.tsx
> +import { EditButton, ProfileAvatar, UploadBox } from '../styles';
done

2022-06-02 09:14 UTC, Yojuks commented on frontend/src/components/Map/ZoomComponent/index.tsx
> +      }
done

2022-06-02 09:14 UTC, Yojuks commented on frontend/src/components/Profile/SaveGroup/SaveGroup.tsx
> +import UploadInputProfilePage from 'components/design/UploadInputProfilePage';
done

2022-06-02 09:14 UTC, mazursasha1990 approved these changes

2022-06-02 09:14 UTC, merged