Feature/map 154/edit personal location
IT-Academy-Social-Projects-KRV/MapUA pull request #134
Opened 2022-06-08 12:25 UTC by Yojuks

you can change data by form-data - locationName, description, arrayPhotos

2022-06-08 12:59 UTC, 6mahdapihka9 requested changes

2022-06-08 12:59 UTC, 6mahdapihka9 commented on backend/controllers/LocationsController.ts
> +
you should delete logs

2022-06-08 12:59 UTC, 6mahdapihka9 commented on backend/controllers/LocationsController.ts
> -      const location = await Location.findById(_id);
will there be an opportunity to change location filters??
if yes - they should be passed in the body as well

2022-06-08 13:35 UTC, Yojuks commented on backend/controllers/LocationsController.ts
> +
done

2022-06-08 13:36 UTC, Yojuks commented on backend/controllers/LocationsController.ts
> -      const location = await Location.findById(_id);
done

2022-06-08 17:16 UTC, obozhko-dev approved these changes

2022-06-08 17:50 UTC, dobbi-free approved these changes

2022-06-09 09:25 UTC, vasylneshchadimov approved these changes

2022-06-10 07:09 UTC, dobbi-free approved these changes

2022-06-10 08:06 UTC, 6mahdapihka9 approved these changes

2022-06-10 08:06 UTC, merged