Feature/map 166/and/map 167/create/user profile/component_and_endpoint
IT-Academy-Social-Projects-KRV/MapUA pull request #136
Opened 2022-06-08 14:01 UTC by romawht22

You can click on user name or avatar in both location popup and comment section to visit their profile

2022-06-08 17:50 UTC, ChikiBum requested changes
When I open Location that I created i saw that
![image](https://user-images.githubusercontent.com/37217530/172683180-c1e7c347-899c-4feb-bed1-698aa0efb594.png)

Date crashed in all locations , this is old problem as i remember or not? 
For own locations should be link to PersonProfile or avatar and name should be not clickable

2022-06-08 17:50 UTC, obozhko-dev commented on frontend/src/components/PersonProfile/PersonProfile.tsx
> +    state => state.userData
Maybe here should be `state.otherUserData` or its correct ? I don`t understand why we using personal user data here

2022-06-08 20:13 UTC, romawht22 commented
> When I open Location that I created i saw that ![image](https://user-images.githubusercontent.com/37217530/172683180-c1e7c347-899c-4feb-bed1-698aa0efb594.png)
> 
> Date crashed in all locations , this is old problem as i remember or not? For own locations should be link to PersonProfile or avatar and name should be not clickable

I think it is corrupted userData in mongo

2022-06-08 20:13 UTC, romawht22 commented on frontend/src/components/PersonProfile/PersonProfile.tsx
> +    state => state.userData
Fixed

2022-06-09 07:36 UTC, ChikiBum approved these changes

2022-06-09 19:56 UTC, vasylneshchadimov approved these changes

2022-06-10 08:11 UTC, merged