Feature/map 191/add filters verified unverified
IT-Academy-Social-Projects-KRV/MapUA pull request #173
Opened 2022-06-24 10:55 UTC by ChikiBum

Added new section and two new filters, translation for filters, processing filters data in backend.

add Scheme (from Andriy) to locations, add data of verificationStatus in mongo, add logic for filterind data to LocationsController.ts

2022-06-24 19:27 UTC, mazursasha1990 requested changes
![Без імені](https://user-images.githubusercontent.com/85229023/175653109-0958cf49-bf7c-4d82-a5a0-0718667923a9.png)
It is an error when you try to choose subscriptions filter

2022-06-26 19:57 UTC, ChikiBum commented
> ![Без імені](https://user-images.githubusercontent.com/85229023/175653109-0958cf49-bf7c-4d82-a5a0-0718667923a9.png) It is an error when you try to choose subscriptions filter

Im fixed it. Problem was in the NestedList component, in OnChange function conditions like as  `if (filterId === 4)`, but I changed mainFIlters object and indexes was changed to . After changed conditions to new index  `if (filterId === 5)` person filters work correctly, but our realization of filters needs to refactor %)

2022-06-27 11:23 UTC, mazursasha1990 approved these changes

2022-06-27 13:50 UTC, naberalgamma approved these changes

2022-06-27 17:31 UTC, Yojuks approved these changes

2022-06-28 09:34 UTC, merged