Feature/map 194/Change marker color for verified, unverified, reported, waiting to verification location
IT-Academy-Social-Projects-KRV/MapUA pull request #178
Opened 2022-06-26 19:32 UTC by nikitius20

2022-06-27 18:01 UTC, Yojuks commented on frontend/src/redux/reducers/popupLocationReducer.tsx
why you added 4 svg - maybe you can add 1 svg and can add className for cases?

2022-06-27 18:01 UTC, Yojuks approved these changes

2022-06-27 20:33 UTC, ChikiBum requested changes

2022-06-27 20:33 UTC, ChikiBum commented on frontend/src/components/LocationPopOut/LocationPopOut.tsx
> +import { verificationStatusTypes } from '../../static/verificationStatusTypes';
For types we have separate file types.ts at the root of the folder front-end. I think this data related to types data and could be in types.ts

2022-06-27 20:33 UTC, ChikiBum commented on frontend/src/components/Map/DrawMarkerWhenLocationCreate/index.tsx
>  // import shadow from '../../../static/leaf-shadow.png';
remove, please, commented code if it didn't using

2022-06-28 08:42 UTC, nikitius20 commented on frontend/src/components/Map/DrawMarkerWhenLocationCreate/index.tsx
>  // import shadow from '../../../static/leaf-shadow.png';
done

2022-06-28 08:52 UTC, nikitius20 commented on frontend/src/redux/reducers/popupLocationReducer.tsx
you can't directly change color in svg.
You can filter a specific folor, but its too complicaed and inefficient, 
But if you want you can check it here https://codepen.io/sosuke/pen/Pjoqqp

2022-06-28 09:17 UTC, ChikiBum approved these changes

2022-06-28 09:25 UTC, merged