Map 192 add filter reporting location fullstack
IT-Academy-Social-Projects-KRV/MapUA pull request #193
Opened 2022-06-30 17:29 UTC by vasylneshchadimov

2022-07-01 05:53 UTC, dobbi-free commented on frontend/src/components/Profile/BasicTabs.tsx
> +          {(role === 'moderator' || role === 'admin') && (
I think it should be in one block. You should wrapp this moderation tabs in fragment

2022-07-01 05:53 UTC, dobbi-free approved these changes

2022-07-01 07:45 UTC, ChikiBum requested changes
1.  maybe the best way use title of tab in one row how it did in another tabs ?
![image](https://user-images.githubusercontent.com/37217530/176847987-dd56a3b3-91be-47bf-b7bf-32977609b087.png)

2. I think not bad add horizontal scroll to tabs , because in smallest screens we have a problem (maybe the problem has another causes, for example fixed width of tabs panel or our profile component, if it is - you can do nothing). Example of scrollable tabs here https://mui.com/material-ui/react-tabs/ in "Scrollable tabs", to do than you need add property variant="scrollable" and specify scrollButtons
![image](https://user-images.githubusercontent.com/37217530/176848821-bceb190f-254c-48c7-bd73-0f7c205eb649.png)

2022-07-01 07:45 UTC, ChikiBum commented on backend/controllers/LocationsController.ts
> +      // }
Remove commented code, pls

2022-07-01 16:54 UTC, vasylneshchadimov commented on backend/controllers/LocationsController.ts
> +      // }
done

2022-07-01 19:55 UTC, Yojuks approved these changes

2022-07-02 09:16 UTC, ChikiBum approved these changes

2022-07-02 09:16 UTC, merged