Feture/map 184/add like or dislike to comments fullstack
IT-Academy-Social-Projects-KRV/MapUA pull request #197
Opened 2022-07-01 16:03 UTC by mazursasha1990

add like or dislike to comments

2022-07-02 08:49 UTC, ChikiBum requested changes

2022-07-02 08:49 UTC, ChikiBum commented on backend/controllers/CommentsController.ts
> +      console.log('id', id);
remove this and next console.log, pls

2022-07-02 08:49 UTC, ChikiBum commented on backend/swagger-config.yml
> +  /comments-rating/:id:
it is cool that you did "swagger"

2022-07-02 18:19 UTC, mazursasha1990 commented on backend/controllers/CommentsController.ts
> +      console.log('id', id);
Done!

2022-07-03 20:55 UTC, naberalgamma approved these changes

2022-07-04 08:09 UTC, ChikiBum approved these changes

2022-07-04 08:18 UTC, Yojuks approved these changes

2022-07-04 08:27 UTC, merged