added layout
IT-Academy-Social-Projects-KRV/MapUA pull request #2
Opened 2022-04-13 16:57 UTC by naberalgamma

2022-04-13 17:18 UTC, steadyGuy requested changes

2022-04-13 17:18 UTC, steadyGuy commented on frontend/package.json
> -    "@mui/icons-material": "^5.6.0",
Honestly saying, you need somehow to setup this package. Maybe try `yarn add @mui/material-icons --network-timeout 500000` (setup big timeout for installation).

2022-04-13 17:18 UTC, steadyGuy commented on frontend/src/App.tsx
> +        <Route path="/Map" element={<Map />} />
I think tat the path should be "/" insted of "Map". But we need to discuss it with team.

2022-04-13 17:18 UTC, steadyGuy commented on frontend/src/App.tsx
> -        <Route path="/" element={<HomeScreen />} />
And why you remove HomeScreen? I thought that we decided to structure our logic as pages (views in our case) and components inside these views.

2022-04-14 08:01 UTC, dobbi-free commented on frontend/src/App.tsx
> -        <Route path="/" element={<HomeScreen />} />
I agree with it. So Map must be in HomePage, and then HomePage in the route.

2022-04-14 09:27 UTC, dobbi-free commented
Replace the component of your Map with a Map from the develop branch

2022-04-14 12:55 UTC, steadyGuy approved these changes

2022-04-14 12:56 UTC, steadyGuy approved these changes
Fix conflicts before merge

2022-04-14 13:12 UTC, romawht22 commented on frontend/src/App.tsx
> +        <Route path="/Map" element={<Map />} />
Why do we need this route?

2022-04-14 13:26 UTC, naberalgamma commented on frontend/src/App.tsx
> +        <Route path="/Map" element={<Map />} />
ok i can remove it

2022-04-14 13:56 UTC, romawht22 approved these changes

2022-04-14 14:27 UTC, merged