Fix/map 232/add button to close adding location mode
IT-Academy-Social-Projects-KRV/MapUA pull request #207
Opened 2022-07-07 10:19 UTC by Yojuks

2022-07-07 11:02 UTC, naberalgamma approved these changes

2022-07-07 11:07 UTC, mazursasha1990 requested changes
It works not correct. When a user pushes the button Add Location and after pushing the map he still sees the yellow button. And after pushing it he still has the ability to add a new location
![YellowButton](https://user-images.githubusercontent.com/85229023/177759449-ac926aa6-a9f9-49db-aaf0-e93a0877a709.png)
.

2022-07-07 11:40 UTC, naberalgamma commented
you need reduce z-index from 15000 to 1000

2022-07-08 07:40 UTC, ChikiBum approved these changes

2022-07-08 11:27 UTC, mazursasha1990 approved these changes

2022-07-08 12:46 UTC, merged