created components to show uploaded images and added logic to remove …
IT-Academy-Social-Projects-KRV/MapUA pull request #222
Opened 2022-07-12 17:35 UTC by 6mahdapihka9

…old ones

2022-07-13 10:40 UTC, naberalgamma commented
add loader to photos in edit mode

2022-07-13 12:04 UTC, mazursasha1990 approved these changes
I didn`t find any issues, without Yuriy's comment.

2022-07-13 13:41 UTC, Yojuks requested changes

2022-07-13 13:41 UTC, Yojuks commented on frontend/src/utils/getFileFromUrl.ts
> +export default getFileFromUrl;
when you open editing location you see this screen
<img width="551" alt="Screenshot 2022-07-13 at 15 03 05" src="https://user-images.githubusercontent.com/39120801/178729395-98e98ab1-8506-4bf1-bc2e-a20f2f6d7e4f.png">
when you press button upload photo you see this
<img width="575" alt="Screenshot 2022-07-13 at 15 03 14" src="https://user-images.githubusercontent.com/39120801/178729504-1b32304f-b40d-4ad7-84c2-8a679d7eb140.png">
and when you save you see this
<img width="563" alt="Screenshot 2022-07-13 at 15 03 33" src="https://user-images.githubusercontent.com/39120801/178729542-0d5c3107-9bd4-4996-97da-3077fbd3d777.png">
i think that new photo maybe to be after previous not before after submit 
i think that new photo should  be after previous not before  - if you think another - can you explaine?

2022-07-14 08:43 UTC, 6mahdapihka9 commented on frontend/src/utils/getFileFromUrl.ts
> +export default getFileFromUrl;
as it should be

2022-07-14 10:01 UTC, Yojuks approved these changes

2022-07-14 10:03 UTC, merged