Refactor frontend to react-redux
IT-Academy-Social-Projects-KRV/MapUA pull request #26
Opened 2022-05-04 15:07 UTC by vasylneshchadimov

2022-05-05 08:46 UTC, steadyGuy requested changes

2022-05-05 08:46 UTC, steadyGuy commented on frontend/src/redux/actions-creators/locationList.ts
> +      const { status, data } = await fetchData(url, options);
instead of fertchData, we decided to use axios, or fetchData should be changed

2022-05-05 08:46 UTC, steadyGuy commented on frontend/src/redux/actions-creators/popupLocation.ts
> +      const { data } = await fetchData(url);
same as prev

2022-05-05 08:46 UTC, steadyGuy commented on frontend/src/redux/types/locationList.ts
> +}
'boundsType' was used before it was defined.eslint[no-use-before-define](https://eslint.org/docs/rules/no-use-before-define)

2022-05-05 08:46 UTC, steadyGuy commented on frontend/src/redux/types/locationList.ts
> +}
for latlngType as well

2022-05-05 08:46 UTC, steadyGuy commented on frontend/src/redux/types/locationList.ts
> +}
And we have had it in types.ts. Why did you comment it? 
![image](https://user-images.githubusercontent.com/41287687/166889767-dc21a858-f90f-4c08-aae4-e521e02553a1.png)

2022-05-05 08:46 UTC, steadyGuy commented on frontend/src/redux/types/locationList.ts
> +};
should be in types.ts

2022-05-05 08:46 UTC, steadyGuy commented on frontend/types.ts
> +// };
uncomment

2022-05-05 12:16 UTC, Yojuks requested changes

2022-05-05 12:16 UTC, Yojuks commented on frontend/types.ts
> +// };
you should fix it - because i can`t start project: there are:
src/redux/types/locationList.ts
  Line 4:11:  'boundsType' was used before it was defined  no-use-before-define
  Line 5:17:  'latlngType' was used before it was defined  no-use-before-define

2022-05-05 21:56 UTC, 6mahdapihka9 requested changes

2022-05-05 21:56 UTC, 6mahdapihka9 commented on frontend/src/redux/actions-creators/locationList.ts
> +        return;
recently on backend that is responsible for this fetch, data's field 'mes' was changed to 'error'

2022-05-05 21:56 UTC, 6mahdapihka9 commented on frontend/src/utils/requests.ts
> +export async function fetchData(option: any) {
actually, this function deprecated due to usage of axios...

2022-05-05 21:56 UTC, 6mahdapihka9 commented on frontend/src/redux/types/locationList.ts
> +//   lng: number;
These comments should be removed

2022-05-06 08:37 UTC, steadyGuy approved these changes

2022-05-06 11:18 UTC, Yojuks requested changes

2022-05-06 11:18 UTC, Yojuks commented on frontend/src/utils/requests.ts
>      console.log(e);
do we need 2 blocks of catch?

2022-05-06 12:26 UTC, 6mahdapihka9 requested changes

2022-05-06 12:26 UTC, 6mahdapihka9 commented on frontend/src/utils/requests.ts
>      console.log(e);
yeap, it looks redundant,

optimization required

2022-05-08 14:02 UTC, Yojuks approved these changes

2022-05-08 15:10 UTC, 6mahdapihka9 approved these changes

2022-05-08 18:00 UTC, merged