Feature/add endpoint personal location
IT-Academy-Social-Projects-KRV/MapUA pull request #29
Opened 2022-05-05 16:57 UTC by Yojuks

2022-05-05 17:09 UTC, steadyGuy approved these changes
Swagger docs for the endpoint needed

2022-05-05 18:27 UTC, romawht22 approved these changes

2022-05-05 21:48 UTC, 6mahdapihka9 approved these changes
pull the latest develop update, because some conflicts may occur

2022-05-05 21:48 UTC, 6mahdapihka9 commented on backend/models/Locations.ts
> +  },
are these commas necessary?

2022-05-05 21:48 UTC, 6mahdapihka9 commented on backend/routes/index.ts
> +  UserController.getUserData
this endpoint changed in last develop update

2022-05-05 21:51 UTC, 6mahdapihka9 requested changes
I'm pretty sure that you should checkout develop

2022-05-06 10:13 UTC, Yojuks commented on backend/models/Locations.ts
> +  },
there were after auto save in vscode

2022-05-06 10:13 UTC, Yojuks commented on backend/routes/index.ts
> +  UserController.getUserData
ok - thanks

2022-05-06 12:23 UTC, 6mahdapihka9 approved these changes

2022-05-06 12:23 UTC, merged