fix-height-Big-popup
IT-Academy-Social-Projects-KRV/MapUA pull request #46
Opened 2022-05-12 12:18 UTC by vasylneshchadimov

2022-05-12 13:56 UTC, Yojuks requested changes

2022-05-12 13:56 UTC, Yojuks commented on frontend/src/components/BigPopup/index.tsx
> +            style: { height: '75vh', marginTop: '85px' }
maybe you should use height 80vh because my screen looks
![Screen Shot 2022-05-12 at 16 54 05](https://user-images.githubusercontent.com/39120801/168092046-34ddc805-6b3a-49f3-936b-fbc186aaf7d7.png)
 like

2022-05-13 12:25 UTC, Yojuks approved these changes

2022-05-13 13:08 UTC, nikitius20 approved these changes

2022-05-13 13:48 UTC, merged