Feature map 109 facebook auth
IT-Academy-Social-Projects-KRV/MapUA pull request #52
Opened 2022-05-16 08:50 UTC by steadyGuy

2022-05-16 09:18 UTC, romawht22 commented on backend/routes/index.ts
> -router.get('/locations/', LocationsController.getLocationsByZoom);
remove post/locations/location-list
and leave get('/locations/'

2022-05-16 13:06 UTC, Yojuks requested changes

2022-05-16 13:06 UTC, Yojuks commented on backend/controllers/AuthController.ts
> +import { v4 as uuidv4 } from "uuid";
you should pull and update - because I added eslint and .prettier to the backend - we use single quotes

2022-05-17 09:19 UTC, romawht22 approved these changes

2022-05-17 09:21 UTC, 6mahdapihka9 approved these changes

2022-05-17 09:21 UTC, Yojuks approved these changes

2022-05-17 09:21 UTC, merged