Feat/map 69/add swagger for the backend add basic configuration
IT-Academy-Social-Projects-KRV/MapUA pull request #6
Opened 2022-04-14 14:20 UTC by mazursasha1990

2022-04-14 14:31 UTC, steadyGuy requested changes
Remove node_modules folder, which located on top of the root foled. _package.json_ and _yarn.lock_ remove too.

2022-04-14 14:31 UTC, steadyGuy commented on backend/README.md
>  _TODO: Add Swagger_
remove todo

2022-04-14 14:31 UTC, steadyGuy commented on backend/index.ts
> +        url: "http://localhost:3001",
Create a varaibale HOST inside .env file (and add this variable to .envExample file) and assign http://localhost:3001 to this variable
then use process.env.HOST

2022-04-14 14:31 UTC, steadyGuy commented on backend/package.json
> +    "@types/swagger-jsdoc": "^6.0.1",
put it in devDependencies

2022-04-14 14:31 UTC, steadyGuy commented on package.json
> +}
Remove this file.

2022-04-14 14:31 UTC, steadyGuy commented on yarn.lock
> +  dependencies:
remvoe this file

2022-04-14 15:21 UTC, steadyGuy requested changes
you didn't remove files that I had mentioned 
![image](https://user-images.githubusercontent.com/41287687/163421783-e8dbc7ac-9950-412b-a81d-e1b76b09a91c.png)

2022-04-14 16:17 UTC, steadyGuy requested changes
Remove node_modules from the top root.
![image](https://user-images.githubusercontent.com/41287687/163431210-5d50b537-eca5-4ae7-9af7-d8a96d58a421.png)

2022-04-14 17:15 UTC, steadyGuy approved these changes

2022-04-15 08:03 UTC, romawht22 approved these changes

2022-04-15 10:17 UTC, merged