Create layout logic for editing profile
IT-Academy-Social-Projects-KRV/MapUA pull request #68
Opened 2022-05-20 15:14 UTC by naberalgamma

2022-05-21 14:21 UTC, 6mahdapihka9 requested changes
check review in Vasyl's PR

2022-05-21 17:23 UTC, Yojuks requested changes

2022-05-21 17:23 UTC, Yojuks commented on frontend/src/components/Profile/BasicTabs.tsx
> +  children?: any;
React.ReactNode - why this code doesn`t work?

2022-05-21 17:23 UTC, Yojuks commented on frontend/src/components/Profile/ProfilePage.tsx
> +      // description
delete

2022-05-21 17:23 UTC, Yojuks commented on frontend/src/components/Profile/styles.ts
>  // import { Typography } from '@mui/material';
delete

2022-05-23 11:01 UTC, Yojuks approved these changes

2022-05-23 13:42 UTC, 6mahdapihka9 approved these changes
👌

2022-05-23 13:42 UTC, merged