big popup
IT-Academy-Social-Projects-KRV/MapUA pull request #7
Opened 2022-04-14 15:44 UTC by vasylneshchadimov

2022-04-14 16:22 UTC, steadyGuy requested changes

2022-04-14 16:22 UTC, steadyGuy commented on frontend/src/components/big popup/index.tsx
> +        <Box sx={{ width: 400, backgroundColor: '#757ce8', mt: 50 }}>
all colors we should get from theme
For example:  _theme.palette.primary.main_
Use seperate style for it or just import theme using useTheme hook from mui

2022-04-14 16:22 UTC, steadyGuy commented on frontend/src/components/big popup/index.tsx
> +export default function BigPopup(props: any) {
Why any?

2022-04-14 16:22 UTC, steadyGuy commented on frontend/src/screens/HomeScreen.tsx
> +import BigPopup from 'components/big popup/index';
Why you call component "big popup"? Using spaces in names is bad practise. Call it BigPopup instead

2022-04-14 17:35 UTC, steadyGuy commented on frontend/src/components/BigPopup/index.tsx
> +  const { isOpen, togleClose } = props;
Variable naming: toggle instead of togle

2022-04-14 17:35 UTC, steadyGuy commented on frontend/src/components/BigPopup/index.tsx
> +  togleClose: any; // this function reatern set of useState
try to use React.Dispatch<React.SetStateAction<boolean>> instead of any. If it does'nt work, remain as any

2022-04-14 17:35 UTC, steadyGuy commented on frontend/src/components/BigPopup/index.tsx
> +  const fon: boolean = true;
variable name "fon", use bg instead, and try not to use cyrillic naming convention

2022-04-14 18:53 UTC, steadyGuy approved these changes

2022-04-15 08:02 UTC, romawht22 approved these changes

2022-04-15 12:20 UTC, Yojuks approved these changes

2022-04-15 12:20 UTC, Yojuks commented on frontend/src/screens/HomeScreen.tsx
> +      <BigPopup isOpen={isOpen} toggleClose={() => setIsopen(false)} />
toggleClose={() => setIsopen(true) - this code working too - why?

2022-04-15 12:20 UTC, Yojuks commented on frontend/src/components/BigPopup/index.tsx
> +  const blackPage: boolean = true;
this const is always true and doesn`t need - we need to rewrite - from hideBackdrop={blackPage} to only hideBackdrop

2022-04-15 12:24 UTC, Yojuks approved these changes

2022-04-15 12:46 UTC, merged