Feature/map 115/add frontend logic for google and facebook 2
IT-Academy-Social-Projects-KRV/MapUA pull request #71
Opened 2022-05-21 19:42 UTC by steadyGuy

2022-05-22 15:28 UTC, romawht22 approved these changes

2022-05-23 10:55 UTC, Yojuks approved these changes

2022-05-23 10:57 UTC, Yojuks requested changes

2022-05-23 10:57 UTC, Yojuks commented on frontend/src/components/Login/Login.tsx
> +  // eslint-disable-next-line no-unused-vars
remove

2022-05-23 11:03 UTC, Yojuks approved these changes

2022-05-23 11:03 UTC, romawht22 approved these changes

2022-05-23 11:03 UTC, merged