Create endpoint for changing in user data without frontend
IT-Academy-Social-Projects-KRV/MapUA pull request #72
Opened 2022-05-22 15:56 UTC by vasylneshchadimov

2022-05-22 18:02 UTC, 6mahdapihka9 commented on backend/routes/index.ts
> +
make it patch method and mb path '/profile' or '/user-data'

2022-05-23 09:48 UTC, Yojuks requested changes

2022-05-23 09:48 UTC, Yojuks commented on backend/routes/index.ts
> +router. patch('/profile',
remove gap

2022-05-23 09:52 UTC, vasylneshchadimov commented on backend/routes/index.ts
> +router. patch('/profile',
done

2022-05-23 10:32 UTC, romawht22 approved these changes

2022-05-23 10:32 UTC, Yojuks approved these changes

2022-05-23 10:37 UTC, merged

2022-05-23 10:53 UTC, steadyGuy approved these changes

2022-05-23 10:53 UTC, steadyGuy commented on backend/controllers/UserController.ts
> +      return res.status(400).json({ error: "User doesn't exist" });
add to translation

2022-05-23 10:53 UTC, steadyGuy approved these changes