Feature map 100 marking locations as visited/favorite
IT-Academy-Social-Projects-KRV/MapUA pull request #73
Opened 2022-05-23 11:22 UTC by nikitius20

Change user schema.
Add logic for adding location to frontend and backend
minor changes in userDataTypes

2022-05-23 17:35 UTC, romawht22 approved these changes

2022-05-24 07:18 UTC, 6mahdapihka9 requested changes
revert changes of user schema

2022-05-24 07:18 UTC, 6mahdapihka9 commented on backend/controllers/UserController.ts
> +      }
should corresponding to language error's message (from Roman's task)

2022-05-24 07:18 UTC, 6mahdapihka9 commented on backend/controllers/UserController.ts
> +      if(userData){
same situation with error here

2022-05-24 07:18 UTC, 6mahdapihka9 commented on backend/models/UserModel.ts
> +  personalLocations: string[];
not required

2022-05-24 07:18 UTC, 6mahdapihka9 commented on backend/models/UserModel.ts
> +      type: []
same

2022-05-24 07:18 UTC, 6mahdapihka9 commented on frontend/src/redux/reducers/userReducer.tsx
> +    personalLocations: []
same

2022-05-24 07:18 UTC, 6mahdapihka9 commented on frontend/types.ts
>  };
same

2022-05-24 07:43 UTC, Yojuks requested changes

2022-05-24 07:43 UTC, Yojuks commented on frontend/src/redux/reducers/userReducer.tsx
> +    visited:[],
should add gap after ":" - because didn`t work

2022-05-24 07:43 UTC, Yojuks commented on frontend/src/components/PointPopup/PointPopup.tsx
> +              <IconButton size="small" onClick={handleFavoriteClick}>
why didn`t add this field to database?

2022-05-24 07:43 UTC, Yojuks commented on frontend/src/components/PointPopup/PointPopup.tsx
> +              <IconButton size="small" onClick={handleVisitedClick}>
too

2022-05-24 08:35 UTC, Yojuks approved these changes

2022-05-24 08:58 UTC, nikitius20 commented on backend/models/UserModel.ts
> +  personalLocations: string[];
what does it mean? should i make them required: true?
what does "revert changes of user schema" mean? should i delete all changes in user schema? they must be there

2022-05-24 09:02 UTC, nikitius20 commented on backend/models/UserModel.ts
> +      type: []
same question here

2022-05-24 09:02 UTC, nikitius20 commented on frontend/src/redux/reducers/userReducer.tsx
> +    personalLocations: []
same question here

2022-05-24 09:03 UTC, nikitius20 commented on frontend/types.ts
>  };
same question here

2022-05-24 10:11 UTC, 6mahdapihka9 approved these changes

2022-05-24 10:14 UTC, merged