Styled file inputs
IT-Academy-Social-Projects-KRV/MapUA pull request #95
Opened 2022-05-26 17:36 UTC by romawht22

2022-05-27 12:04 UTC, naberalgamma approved these changes

2022-05-27 13:57 UTC, ChikiBum reviewed
1. In Profile page when I tap to "Edit profile" button , image moved to right side 
![image](https://user-images.githubusercontent.com/37217530/170713204-99f6be48-9db3-406f-b287-ade19cb1205c.png)

2. In "Create location" window I can add only one photo now. If i didn't mistake Andrey did functionality to download more than 1 photo. Сheck with him, please, you need to upload one photo or many?

2022-05-27 16:03 UTC, Yojuks requested changes

2022-05-27 16:03 UTC, Yojuks commented on frontend/src/components/CreateLocation/CreateLocation.tsx
> +                (ref.current?.files && ref.current?.files[0].name) || ''
you should add items-alient: center to this block if you use flex

2022-05-30 06:05 UTC, 6mahdapihka9 reviewed
I think you should create the whole component that includes button and hiddenInput and takes props like title, onChange etc. as mui objects. That will make it more reusable and convenient

2022-05-30 06:05 UTC, 6mahdapihka9 commented on frontend/src/components/Profile/ProfilePage.tsx
>                  <Box>
what is it for?

2022-05-30 11:12 UTC, Yojuks commented on frontend/src/components/design/UploadInputProfilePage/index.tsx
> +};
<img width="1536" alt="Screenshot 2022-05-30 at 14 02 49" src="https://user-images.githubusercontent.com/39120801/170980493-21dace69-ebd0-4700-b6d6-b4d591e0516a.png">м
<img width="470" alt="Screenshot 2022-05-30 at 14 08 24" src="https://user-images.githubusercontent.com/39120801/170980511-7dc8a35a-a7e9-47a7-a71b-b76073833db6.png">
text and button maybe should be by center)

2022-05-30 11:19 UTC, Yojuks approved these changes

2022-05-30 12:05 UTC, 6mahdapihka9 approved these changes
norm

2022-05-30 12:15 UTC, merged