Add_404_route
IT-Academy-Social-Projects-KRV/MapUA pull request #98
Opened 2022-05-27 22:55 UTC by vasylneshchadimov

2022-05-29 18:34 UTC, 6mahdapihka9 requested changes

2022-05-29 18:34 UTC, 6mahdapihka9 commented on frontend/src/components/Profile/ProfilePage.tsx
>  import {
I prefer the previous version of the unknown user's image

2022-05-29 21:22 UTC, 6mahdapihka9 commented on frontend/src/components/Profile/ProfilePage.tsx
>  import {
done

2022-05-29 21:22 UTC, 6mahdapihka9 approved these changes

2022-05-30 07:11 UTC, Yojuks approved these changes
Сongratulations on the configure 'prettier')

2022-05-30 08:13 UTC, merged